# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sd_gsl <- function(mx) {
    .Call(`_yeastfitness_sd_gsl`, mx)
}

one_if_zero <- function(x) {
    .Call(`_yeastfitness_one_if_zero`, x)
}

sd_cpp <- function(x) {
    .Call(`_yeastfitness_sd_cpp`, x)
}

standardize_matrix_cpp <- function(matx) {
    .Call(`_yeastfitness_standardize_matrix_cpp`, matx)
}

spearman_rho_cpp <- function(mx, i, j) {
    .Call(`_yeastfitness_spearman_rho_cpp`, mx, i, j)
}

pearson_correlation_cpp <- function(mx, i, j) {
    .Call(`_yeastfitness_pearson_correlation_cpp`, mx, i, j)
}

get_rho_cpp <- function(mx) {
    .Call(`_yeastfitness_get_rho_cpp`, mx)
}

get_sub_SCS_cpp <- function(mx) {
    .Call(`_yeastfitness_get_sub_SCS_cpp`, mx)
}

get_SCS_cpp <- function(mx) {
    .Call(`_yeastfitness_get_SCS_cpp`, mx)
}

get_ASR_cpp <- function(mx) {
    .Call(`_yeastfitness_get_ASR_cpp`, mx)
}

get_VET_cpp <- function(matx) {
    .Call(`_yeastfitness_get_VET_cpp`, matx)
}

get_vol_seridi <- function(matrix, data_mt, alpha, beta) {
    .Call(`_yeastfitness_get_vol_seridi`, matrix, data_mt, alpha, beta)
}

get_vol_pontes <- function(matrix, genes_weight, cond_weight) {
    .Call(`_yeastfitness_get_vol_pontes`, matrix, genes_weight, cond_weight)
}

print_test <- function() {
    .Call(`_yeastfitness_print_test`)
}

test_mean <- function(mx) {
    .Call(`_yeastfitness_test_mean`, mx)
}

test_sd <- function(mx) {
    .Call(`_yeastfitness_test_sd`, mx)
}

